name: linux

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ '*' ]

jobs:

  perl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
        - '5.42-bookworm'

    container:
      image: perl:${{ matrix.perl-version }}

    steps:
    - uses: actions/checkout@v3
    - run: env | sort
    - run: perl -V
    - &installdeps
      name: Install deps
      run: >
        cpanm --quiet --notest
        Getopt::Long::Descriptive YAML::PP Test2::V0
    - name: Run Tests
      run: prove -lr t

  cover:
    runs-on: ubuntu-latest
    container:
      image: perl:5.42

    steps:
    - uses: actions/checkout@v3

    - *installdeps
    - name: Install coverage deps
      run: >
        cpanm --quiet --notest
        Devel::Cover Devel::Cover::Report::Codecovbash
    - name: Run Tests
      run: >
        PERL5OPT="-MDevel::Cover=-db,cover_db,-select,^lib,-ignore,^t/|bin/prove|^examples"
        prove -lr t

        cover -report codecovbash
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: ./cover_db/codecov.json
        fail_ci_if_error: true
        verbose: true

